version: "3.8"
name: registry
services:
  registry:
    container_name: registry
    image: registry:2.8
    env_file: .env
    restart: always
    ports:
      - ${APP_PORT}:5000
    volumes:
      - ./registry:/var/lib/registry
    extra_hosts:
      - host.docker.internal:host-gateway
